Repository hetznercloud/terraform-provider-hcloud, pull requests merged in 2018-11, with the labels that each got.

#41 Fix wrong release badge on readme
  README.md
Labels: size/XS

#47 Add volume_attachment resource
  hcloud/provider.go
  hcloud/resource_hcloud_floatingip_assignment.go
  hcloud/resource_hcloud_volume.go
  hcloud/resource_hcloud_volume_attachment.go
  hcloud/resource_hcloud_volume_attachment_test.go
  hcloud/resource_hcloud_volume_test.go
  website/docs/r/volume_attachment.html.md
  website/hcloud.erb
Labels: size/L

#48 Update hcloud-go to new version
  Gopkg.lock
  Gopkg.toml
  hcloud/resource_hcloud_server.go
  hcloud/resource_hcloud_volume.go
  vendor/github.com/hetznercloud/hcloud-go/.travis.yml
  vendor/github.com/hetznercloud/hcloud-go/CHANGES.md
  vendor/github.com/hetznercloud/hcloud-go/hcloud/action.go
  vendor/github.com/hetznercloud/hcloud-go/hcloud/datacenter.go
  vendor/github.com/hetznercloud/hcloud-go/hcloud/floating_ip.go
  vendor/github.com/hetznercloud/hcloud-go/hcloud/hcloud.go
  vendor/github.com/hetznercloud/hcloud-go/hcloud/image.go
  vendor/github.com/hetznercloud/hcloud-go/hcloud/location.go
  vendor/github.com/hetznercloud/hcloud-go/hcloud/schema.go
  vendor/github.com/hetznercloud/hcloud-go/hcloud/schema/server.go
  vendor/github.com/hetznercloud/hcloud-go/hcloud/schema/volume.go
  vendor/github.com/hetznercloud/hcloud-go/hcloud/schema_test.go
  vendor/github.com/hetznercloud/hcloud-go/hcloud/server.go
  vendor/github.com/hetznercloud/hcloud-go/hcloud/server_test.go
  vendor/github.com/hetznercloud/hcloud-go/hcloud/server_type.go
  vendor/github.com/hetznercloud/hcloud-go/hcloud/ssh_key.go
  vendor/github.com/hetznercloud/hcloud-go/hcloud/volume.go
  vendor/github.com/hetznercloud/hcloud-go/hcloud/volume_test.go
Labels: size/L

#49 Prepare Changelog for Release 1.5.0
  CHANGELOG.md
Labels: size/XS

#52 add most_recent option to images datasource
  CHANGELOG.md
  hcloud/data_source_hcloud_image.go
  hcloud/data_source_hcloud_image_test.go
  website/docs/d/image.html.md
Labels: enhancement, size/S
