Repository hetznercloud/terraform-provider-hcloud, pull requests merged in 2018-09, with the labels that each got.

#28 Implement datasources and labels
  Gopkg.lock
  Gopkg.toml
  hcloud/data_source_hcloud_floatingip.go
  hcloud/data_source_hcloud_floatingip_test.go
  hcloud/data_source_hcloud_image.go
  hcloud/data_source_hcloud_image_test.go
  hcloud/data_source_hcloud_sshkey.go
  hcloud/data_source_hcloud_sshkey_test.go
  hcloud/provider.go
  hcloud/resource_hcloud_floatingip.go
  hcloud/resource_hcloud_server.go
  hcloud/resource_hcloud_sshkey.go
  vendor/github.com/hetznercloud/hcloud-go/CHANGES.md
  vendor/github.com/hetznercloud/hcloud-go/hcloud/client.go
  vendor/github.com/hetznercloud/hcloud-go/hcloud/floating_ip.go
  vendor/github.com/hetznercloud/hcloud-go/hcloud/floating_ip_test.go
  vendor/github.com/hetznercloud/hcloud-go/hcloud/hcloud.go
  vendor/github.com/hetznercloud/hcloud-go/hcloud/image.go
  vendor/github.com/hetznercloud/hcloud-go/hcloud/image_test.go
  vendor/github.com/hetznercloud/hcloud-go/hcloud/schema.go
  vendor/github.com/hetznercloud/hcloud-go/hcloud/schema/floating_ip.go
  vendor/github.com/hetznercloud/hcloud-go/hcloud/schema/image.go
  vendor/github.com/hetznercloud/hcloud-go/hcloud/schema/server.go
  vendor/github.com/hetznercloud/hcloud-go/hcloud/schema/ssh_key.go
  vendor/github.com/hetznercloud/hcloud-go/hcloud/schema_test.go
  vendor/github.com/hetznercloud/hcloud-go/hcloud/server.go
  vendor/github.com/hetznercloud/hcloud-go/hcloud/server_test.go
  vendor/github.com/hetznercloud/hcloud-go/hcloud/ssh_key.go
  vendor/github.com/hetznercloud/hcloud-go/hcloud/ssh_key_test.go
  website/docs/d/image.html.md
  website/docs/d/ssh_key.html.md
  website/docs/r/server.html.md
  website/hcloud.erb
Labels: size/XXL

#30 Added argument and attribute value types to docs
  website/docs/d/floating_ip.html.md
  website/docs/d/image.html.md
  website/docs/d/ssh_key.html.md
  website/docs/index.html.markdown
  website/docs/r/floating_ip.html.md
  website/docs/r/floating_ip_assignment.html.md
  website/docs/r/rdns.html.md
  website/docs/r/server.html.md
  website/docs/r/ssh_key.html.md
Labels: size/L

#32 Add sample for label selector to the documentation
  website/docs/d/floating_ip.html.md
  website/docs/d/image.html.md
  website/docs/d/ssh_key.html.md
Labels: size/S
