Repository hetznercloud/terraform-provider-hcloud, pull requests merged in 2019-07, with the labels that each got.

#90 Add networks support
  CHANGELOG.md
  GNUmakefile
  go.mod
  go.sum
  hcloud/data_source_hcloud_network.go
  hcloud/data_source_hcloud_network_test.go
  hcloud/import_hcloud_network_test.go
  hcloud/provider.go
  hcloud/resource_hcloud_network.go
  hcloud/resource_hcloud_network_route.go
  hcloud/resource_hcloud_network_route_test.go
  hcloud/resource_hcloud_network_subnet.go
  hcloud/resource_hcloud_network_subnet_test.go
  hcloud/resource_hcloud_network_test.go
  hcloud/resource_hcloud_server_network.go
  hcloud/resource_hcloud_server_network_test.go
  vendor/github.com/hetznercloud/hcloud-go/hcloud/client.go
  vendor/github.com/hetznercloud/hcloud-go/hcloud/error.go
  vendor/github.com/hetznercloud/hcloud-go/hcloud/floating_ip.go
  vendor/github.com/hetznercloud/hcloud-go/hcloud/hcloud.go
  vendor/github.com/hetznercloud/hcloud-go/hcloud/location.go
  vendor/github.com/hetznercloud/hcloud-go/hcloud/network.go
  vendor/github.com/hetznercloud/hcloud-go/hcloud/schema.go
  vendor/github.com/hetznercloud/hcloud-go/hcloud/schema/floating_ip.go
  vendor/github.com/hetznercloud/hcloud-go/hcloud/schema/location.go
  vendor/github.com/hetznercloud/hcloud-go/hcloud/schema/network.go
  vendor/github.com/hetznercloud/hcloud-go/hcloud/schema/server.go
  vendor/github.com/hetznercloud/hcloud-go/hcloud/server.go
  vendor/modules.txt
  website/docs/d/network.html.md
  website/docs/r/floating_ip.html.md
  website/docs/r/network.html.md
  website/docs/r/network_route.html.md
  website/docs/r/network_subnet.html.md
  website/docs/r/server.html.md
  website/docs/r/server_network.html.md
  website/hcloud.erb
Labels: dependencies, documentation, size/XXL

#99 Update CHANGELOG.md
  CHANGELOG.md
Labels: size/XS

#101 Correct link to documentation for hcloud_server_network
  website/hcloud.erb
Labels: documentation, size/XS

#106 Bugfix for private isos
  hcloud/resource_hcloud_server.go
  hcloud/resource_hcloud_server_test.go
  website/docs/d/server.html.md
  website/docs/r/server.html.md
Labels: documentation, size/M

#107 Allow usage of hcloud-go debugging via TF_LOG
  go.mod
  hcloud/provider.go
Labels: size/XS

#108 Add mac_address to hcloud_server_network
  CHANGELOG.md
  hcloud/resource_hcloud_server_network.go
  hcloud/resource_hcloud_server_network_test.go
Labels: size/XS

#103 hcloud_ssh_keys datasource
  hcloud/data_source_hcloud_sshkey.go
  hcloud/data_source_hcloud_sshkeys.go
  hcloud/data_source_hcloud_sshkeys_test.go
  hcloud/provider.go
  website/docs/d/ssh_keys.html.md
Labels: documentation, size/L
