Repository hetznercloud/terraform-provider-hcloud, pull requests merged in 2019-02, with the labels that each got.

#66 Fix typo on datacenter name
  website/docs/r/rdns.html.md
Labels: documentation, size/XS

#65 [AUTOMATED] Upgrade to Go 1.11
  .travis.yml
  README.md
  hcloud/data_source_hcloud_image_test.go
Labels: size/XS

#69 Add hcloud_server datasource
  CHANGELOG.md
  hcloud/data_source_hcloud_server.go
  hcloud/data_source_hcloud_server_test.go
  hcloud/provider.go
  hcloud/resource_hcloud_server.go
  website/docs/d/server.html.md
  website/hcloud.erb
Labels: documentation, new-data-source, size/XL

#70 Add api token length validation
  CHANGELOG.md
  hcloud/provider.go
Labels: size/XS
