Repository hetznercloud/terraform-provider-hcloud, pull requests merged in 2019-09, with the labels that each got.

#120 Add Floating IP Name support
  CHANGELOG.md
  hcloud/data_source_hcloud_floatingip.go
  hcloud/data_source_hcloud_floatingip_test.go
  hcloud/provider.go
  hcloud/resource_hcloud_floatingip.go
  hcloud/resource_hcloud_floatingip_test.go
Labels: size/M

#121 Use Go 1.13 for testing and building
  .go-version
  .travis.yml
  CHANGELOG.md
  README.md
Labels: size/XS

#124 typo fix
  website/docs/index.html.markdown
Labels: documentation, size/XS

#123 Fix typos in ssh key datasources
  website/docs/d/ssh_key.html.md
  website/docs/d/ssh_keys.html.md
Labels: documentation, size/XS
