Repository hetznercloud/terraform-provider-hcloud, pull requests merged in 2020-07, with the labels that each got.

#174 Fix HTTP health check defaults
  CHANGELOG.md
  hcloud/resource_hcloud_load_balancer_service.go
  hcloud/resource_hcloud_load_balancer_target_test.go
  website/docs/r/load_balancer_service.html.md
Labels: documentation, size/XS

#181 Prepare Release v1.18.1
  CHANGELOG.md
  hcloud/provider.go
Labels: size/XS

#180 force recreate of hcloud_network if ip_range changes
  CHANGELOG.md
  hcloud/resource_hcloud_network.go
Labels: size/XS

#192 Rework load balancer tests
  hcloud/data_source_hcloud_load_balancer_test.go
  hcloud/import_hcloud_load_balancer_test.go
  hcloud/provider_test.go
  hcloud/resource_hcloud_load_balancer_network_test.go
  hcloud/resource_hcloud_load_balancer_service.go
  hcloud/resource_hcloud_load_balancer_service_test.go
  hcloud/resource_hcloud_load_balancer_target_test.go
  hcloud/resource_hcloud_load_balancer_test.go
  hcloud/resource_hcloud_network_test.go
  hcloud/resource_hcloud_server_network.go
  hcloud/resource_hcloud_server_test.go
  internal/certificate/resoruce.go
  internal/certificate/testing.go
  internal/loadbalancer/data_source.go
  internal/loadbalancer/data_source_test.go
  internal/loadbalancer/resource.go
  internal/loadbalancer/resource_network.go
  internal/loadbalancer/resource_network_test.go
  internal/loadbalancer/resource_service.go
  internal/loadbalancer/resource_service_test.go
  internal/loadbalancer/resource_target.go
  internal/loadbalancer/resource_target_test.go
  internal/loadbalancer/resource_test.go
  internal/loadbalancer/testing.go
  internal/network/resource.go
  internal/network/testing.go
  internal/server/resource.go
  internal/server/testing.go
  internal/testdata/d/hcloud_load_balancer.tf.tmpl
  internal/testdata/r/hcloud_certificate.tf.tmpl
  internal/testdata/r/hcloud_load_balancer.tf.tmpl
  internal/testdata/r/hcloud_load_balancer_network.tf.tmpl
  internal/testdata/r/hcloud_load_balancer_service.tf.tmpl
  internal/testdata/r/hcloud_load_balancer_target.tf.tmpl
  internal/testdata/r/hcloud_network.tf.tmpl
  internal/testdata/r/hcloud_network_subnet.tf.tmpl
  internal/testdata/r/hcloud_server.tf.tmpl
  internal/testdata/r/hcloud_server_network.tf.tmpl
  internal/testsupport/check.go
  internal/testsupport/common.go
  internal/testsupport/dir.go
  internal/testsupport/dir_test.go
  internal/testtemplate/dirs.go
  internal/testtemplate/dirs_test.go
  internal/testtemplate/template.go
  website/docs/r/load_balancer.html.md
Labels: size/XXL
